name: IIS Build and Deploy

on:
	workflow_call:
		inputs:
			language:
				description: 'Language implementation: dotnet | netframework'
				required: true
				type: string
			projects:
				description: 'JSON array describing the projects to publish'
				required: true
				type: string
			artifacts:
				description: 'JSON array describing the artifacts to upload'
				required: false
				default: '[]'
				type: string

jobs:
	build-publish:
		uses: ./workflows/common/build-publish.yml
		with:
			language: ${{ inputs.language }}
			projects: ${{ inputs.projects }}
			artifacts: ${{ inputs.artifacts }}

	deploy:
		needs: build-publish
		runs-on: windows-latest
		steps:
			- name: Checkout repository
				uses: actions/checkout@v4
