name: Code Analysis Test

on:
  workflow_call:
    inputs:
      language:
        description: 'Language implementation: dotnet | netframework'
        required: true
        type: string
      variables:
        description: 'JSON object with the repository variables'
        required: false
        default: '{}'
        type: string

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build .NET
        if: ${{ inputs.language == 'dotnet' }}
        uses: YelcoBotCompany/devops-core/templates/dotnet/build@main
        with:
          solution: ${{ fromJSON(inputs.variables).SOLUTION }}
          configuration: ${{ fromJSON(inputs.variables).CONFIGURATION }}
          platform: ${{ fromJSON(inputs.variables).PLATFORM }}
      - name: Test .NET
        if: ${{ inputs.language == 'dotnet' }}
        uses: YelcoBotCompany/devops-core/templates/dotnet/test@main
        with:
          solution: ${{ fromJSON(inputs.variables).SOLUTION }}
          configuration: ${{ fromJSON(inputs.variables).CONFIGURATION }}
          platform: ${{ fromJSON(inputs.variables).PLATFORM }}
      - name: Build .NET Framework
        if: ${{ inputs.language == 'netframework' }}
        uses: YelcoBotCompany/devops-core/templates/netframework/build@main
        with:
          solution: ${{ fromJSON(inputs.variables).SOLUTION }}
          configuration: ${{ fromJSON(inputs.variables).CONFIGURATION }}
          platform: ${{ fromJSON(inputs.variables).PLATFORM }}
      - name: Test .NET Framework
        if: ${{ inputs.language == 'netframework' }}
        uses: YelcoBotCompany/devops-core/templates/netframework/test@main
        with:
          vstest-platform: ${{ fromJSON(inputs.variables).VSTEST_PLATFORM }}