name: Build, Publish, and Upload Artifacts

on:
  workflow_call:
    inputs:
      language:
        description: 'Language implementation: dotnet | netframework'
        required: true
        type: string

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build .NET
        if: ${{ inputs.language == 'dotnet' }}
        uses: YelcoBotCompany/devops-core/templates/dotnet/build@main
      - name: Test .NET
        if: ${{ inputs.language == 'dotnet' }}
        uses: YelcoBotCompany/devops-core/templates/dotnet/test@main
      - name: Build .NET Framework
        if: ${{ inputs.language == 'netframework' }}
        uses: YelcoBotCompany/devops-core/templates/netframework/build@main
      - name: Test .NET Framework
        if: ${{ inputs.language == 'netframework' }}
        uses: YelcoBotCompany/devops-core/templates/netframework/test@main