name: Visual Studio Marketplace Command Router

on:
  workflow_call:
    inputs:
      service:
        description: 'Target service'
        required: true
        type: string
      language:
        description: 'Language implementation: dotnet | netframework'
        required: true
        type: string
      command:
        description: 'Command to execute'
        required: false
        default: ''
        type: string
      projects:
        description: 'JSON array describing the projects'
        required: false
        default: '[]'
        type: string
      artifacts:
        description: 'JSON array describing the artifacts'
        required: false
        default: '[]'
        type: string

jobs:
  deploy:
    if: ${{ inputs.command == 'deploy' }}
    uses: YelcoBotCompany/devops-core/.github/workflows/visual-studio-marketplace-deploy.yml@main
    with:
      language: ${{ inputs.language }}
      projects: ${{ inputs.projects }}
      artifacts: ${{ inputs.artifacts }}
